Add new languages and translation
QuasarApp/Hanoi-Towers pull request #99
Opened 2021-05-31 06:03 UTC by Oleg-designer

fix #97

2021-05-31 06:12 UTC, EndrII approved these changes

2021-05-31 06:14 UTC, EndrII requested changes
please add translation for descriptions

2021-06-01 08:02 UTC, pzhlkj6612 commented
Hi, please merge #100 to add the human translation of Chinese.

2021-06-01 08:27 UTC, EndrII approved these changes

2021-06-01 08:32 UTC, merged